### ISSUE TITLE
缺少查找表文件

### ISSUE THREAD

**Issue by shazi4399** [xingpz2008/TriFSS#1]
你好，我在跑`Benchmark/Proximity_test.py`测试。

报错信息提示`No such file or directory: '../Assets/publicSinCoefficients_16_10.lut'`,这个应该怎么解决呢，你可以分享下这个查找表文件吗

完整报错信息如下：
```bash
Traceback (most recent call last):
  File "/home/zhanghao/Downloads/mycode/TriFSS/Benchmark/Proximity_test.py", line 42, in <module>
    proximity_test([4.52, 2.78], [0.53, 8.44])
  File "/home/zhanghao/Downloads/mycode/TriFSS/Benchmark/Proximity_test.py", line 25, in proximity_test
    front_ = clear_sin(front_operand)
  File "/home/zhanghao/Downloads/mycode/TriFSS/Pythonic_TriFSS/Cleartext/cleartext_functions.py", line 21, in clear_sin
    coefficients: LookUpTable = api.local_recv(f'publicSinCoefficients_{repr_config.bitlen}_'
  File "/home/zhanghao/Downloads/mycode/TriFSS/Pythonic_TriFSS/Communication/api.py", line 119, in local_recv
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../Assets/publicSinCoefficients_16_10.lut'
```

**Comment by xingpz2008** [comment]
你好，查找表可以调用[Utils/construct_LUT.py](https://github.com/xingpz2008/TriFSS/blob/main/Utils/construct_LUT.py) 中的对应函数生成

**Comment by shazi4399** [comment]
非常感谢你，这个问题解决了，我通过以下步骤解决的：

step1：
我写了一个`generate_lookuptable.py`脚本，源代码如下：
```python
import Pythonic_TriFSS.Utils.construct_LUT as construct_LUT

construct_LUT.sin_coefficients(True)
construct_LUT.sin_val(True)
construct_LUT.cos_coefficients(True)
construct_LUT.cos_val(True)
construct_LUT.tan_coefficients(True)
construct_LUT.tan_val(True)
```
step2.`generate_lookuptable.py`脚本执行后，会在`Assets/`文件夹下生成`****.lut`文件

step3.我再次运行`Benchmark/Proximity_test.py`,发现结果输出0。

我新的疑问是，这个0是符合预期的输出结果吗？

**Comment by xingpz2008** [comment]
> 非常感谢你，这个问题解决了，我通过以下步骤解决的：
> 
> step1： 我写了一个`generate_lookuptable.py`脚本，源代码如下：
> 
> ```python
> import Pythonic_TriFSS.Utils.construct_LUT as construct_LUT
> 
> construct_LUT.sin_coefficients(True)
> construct_LUT.sin_val(True)
> construct_LUT.cos_coefficients(True)
> construct_LUT.cos_val(True)
> construct_LUT.tan_coefficients(True)
> construct_LUT.tan_val(True)
> ```
> 
> step2.`generate_lookuptable.py`脚本执行后，会在`Assets/`文件夹下生成`****.lut`文件
> 
> step3.我再次运行`Benchmark/Proximity_test.py`,发现结果输出0。
> 
> 我新的疑问是，这个0是符合预期的输出结果吗？

此脚本最后输出的结果是ULP Error，表示误差值，0符合预期。
关于ULP Error，可以阅读相关文献了解更多信息

**Comment by shazi4399** [comment]
明白了，感谢！
